# Economic Development Licences Data Processing 


## Where are the cityâ€™s economic development licenses? Which communities are benefitting? Which communities are being left out?

Project Deliverable 1 (Due: 10/15)
Sufficient data should have been collected to perform a preliminary analysis of the data and attempt to answer one question relevant to your project proposal which you will submit as a pull request. If data has already been collected for your project you must answer two questions.
Checklist: 
- Collect and pre-process a preliminary batch of data
- Perform a preliminary analysis of the data
- Answer one key question
- Refine project scope and list of limitations with data and potential risks of achieving project goal
- Submit a PR with the above report and modifications to original proposal

In [2]:
import pandas as pd
import numpy as np
import csv

# pre-processing steps:

# reading the dataframe 
df1 = pd.read_csv('alcohol_licences.csv')
df2 = pd.read_csv('cannabis_licences.csv')
df3 = pd.read_csv('food_licences.csv')
df4 = pd.read_csv('licensing_board_licences.csv')

In [3]:
# understanding the data : categorical vals and numeric vals
print(df1.keys())
print(df1.aggregate)

Index(['license_num', 'historicallicensenum', 'status', 'license_type',
       'issued', 'expires', 'business_name', 'dba_name', 'comments',
       'location_comments', 'opening', 'closing', 'patronsout', 'capacity',
       'applicant', 'manager', 'day_phone', 'evening_phone', 'address', 'city',
       'state', 'zip', 'gpsx', 'gpsy'],
      dtype='object')
<bound method DataFrame.aggregate of      license_num historicallicensenum  status  \
0      LB-485386                  NaN  Active
1      LB-481088                  NaN  Active
2      LB-476655                  NaN  Active
3      LB-445763                  NaN  Active
4      LB-483679                  NaN  Active
...          ...                  ...     ...
1441   LB-101610           GOPWML0008  Active
1442   LB-101596            GOPWM0004  Active
1443   LB-101611           GOPWML0009  Active
1444   LB-102890           SPCMWA0012  Active
1445   LB-101595            GOPWM0001  Active

                          license_type      issued     expires  \
0                     Retail Malt Wine         NaN         NaN
1     CV7ALN - Neighborhood Restricted  2022-09-29  2022-12-31
2     CV7ALN - Neighborhood Restricted  2022-09-26  2022-12-31
3                     Retail Malt Wine  2022-08-30  2022-12-31
4                   CV7 All Alc. Airp.  2022-08-24  2022-12-31
...                                ...         ...         ...
1441                GOP Malt Wine Liq.  2013-10-01  2022-12-31
1442                GOP Malt Wine Liq.  2013-10-01  2022-12-31
1443                GOP Malt Wine Liq.  2013-10-01  2022-12-31
1444                            SPCMWA  2013-10-01  2022-12-31
1445                     GOP Malt Wine  2013-10-01  2022-12-31

                    business_name                          dba_name  \
0           Dorchester Market LLC                 Dorchester Market
1                   Yak Thai Inc.                          Thonglor
2     HOMESTEAD BAKERY & CAFE LLC                               NaN
3          Grove Hall Foods Corp.  Grove Hall Convenience Market II
4          PremAir of Boston, LLC                  Harpoon Tap Room
...                           ...                               ...
1441              EMERSON COLLEGE                   EMERSON COLLEGE
1442  BOSTON CULINARY GROUP, INC.               THE ORPHEUM THEATRE
1443     EMANUEL ENTERPRISES, LLC                               NaN
1444      HARVARD BUSINESS SCHOOL         YEAR-ROUND RETAIL & CATER
1445          LYRIC STAGE COMPANY                       LYRIC STAGE

                                               comments  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
1441  MUST RECEIVE PRIOR WRITTEN PERMISSION BOARD AN...
1442  1 CONSUMPTION ALCOHOL ALLOWED IN SEATING AREA ...
1443                                                NaN
1444                                                NaN
1445                                       11 00 M to P

                                      location_comments  ...  \
0     Accessory retail sales of wine & malt beverage...  ...
1     1,000SF: in one room on first floor (seating f...  ...
2     homestead bakery & cafe LLC is located on the ...  ...
3                                                   NaN  ...
4     Logan International Airport, Terminal A, space...  ...
...                                                 ...  ...
1441  WITHIN THE CUTLER MAJESTIC THEATRE AUDITORIUM ...  ...
1442  IN WHOLE OF ORPHEUM THEATRE, INCLUDING BAR SER...  ...
1443  Entrance on first floor;  one room on first fl...  ...
1444                                                NaN  ...
1445  140 CLARENDON STREET; ON THE SECOND FLOOR THEA...  ...

                         applicant                          manager  \
0            Dorchester Market LLC                      Peter McGee
1                    Yak Thai Inc.                  Piyapong Wongla
2      homestead bakery & cafe LLC                         Annie Le
3           Grove Hall Foods Corp.                  Edward Guerrero
4          PremAir of Boston, LLC.   Kelliann Van Kleeck McClintock
...                            ...                              ...
1441               EMERSON COLLEGE                      DAVID DOWER
1442   BOSTON CULINARY GROUP, INC.                     Sean O'Dwyer
1443      EMANUEL ENTERPRISES, LLC                     EDGAR OSPINA
1444       HARVARD BUSINESS SCHOOL                      Todd Mulder
1445           LYRIC STAGE COMPANY                    Matt Chapuran

          day_phone  evening_phone                address         city state  \
0     (617)238-7406            NaN    951-  Dorchester AV   Dorchester    MA
1     (781)472-0835            NaN    559-  Washington ST     Brighton    MA
2     (617)858-0468            NaN  1448-  Dorchester AVE   Dorchester    MA
3     (617)708-0775            NaN      292-   Talbot AVE       Boston    MA
4     (305)898-7414            NaN    100     Terminal RD  East Boston    MA
...             ...            ...                    ...          ...   ...
1441            NaN  (617)894-6100      219-   Tremont ST       Boston    MA
1442            NaN  (781)659-9923        1-  Hamilton Pl       Boston    MA
1443            NaN  (617)608-0899     71-73  Meridian ST  East Boston    MA
1444            NaN  (781)334-2856    117     Western AVE       Boston    MA
1445            NaN       776-8280    140-   Clarendon ST       Boston    MA

        zip           gpsx          gpsy
0     02125  775975.718316  2.941310e+06
1     02135  747073.290888  2.952562e+06
2     02122  775264.770142  2.935071e+06
3     02124  771330.817625  2.931370e+06
4     02128  785396.803968  2.958230e+06
...     ...            ...           ...
1441  02116  773745.402268  2.953441e+06
1442  02108  774839.371862  2.955136e+06
1443  02128  780787.801708  2.960911e+06
1444  02135  758260.000014  2.958325e+06
1445  02116  771204.999994  2.952350e+06

[1446 rows x 24 columns]>

In [4]:
print(df2.keys())
print(df2.aggregate)

Index(['Main Entity Name', 'Trade Name DBA', 'Facility Address',
       'Facility Neighborhood', 'Facility Zip Code',
       'Type of Marijuana License', 'Application Status',
       'Seeking Bos Equity Program', 'Submitted Date', 'Map Location',
       'Main Contact Full Name', 'First Contact Full Name',
       'Second Contact Full Name', 'Third Contact Full Name'],
      dtype='object')
<bound method DataFrame.aggregate of                                       Main Entity Name  \
0                            1220 WASHINGTON ST., INC.
1                           684 Center Street, JP, LLC
2    Apothca, Inc. f/k/a Massachusetts Patient Foun...
3                                          Baba Ku llc
4                           Bay State Herbal Solutions
..                                                 ...
149                               The Grazin Group LLC
150                                    The Hempest LLC
151                                   The Hempest, LLC
152                              Union Twist, Inc..\n
153                             Verdant  Medical Inc..

                   Trade Name DBA  \
0    The Boston Garden Dispensary
1               Prolific Cannabis
2                   Apothca, Inc.
3                         Baba Ku
4                             NaN
..                            ...
149                           NaN
150                           NaN
151                           NaN
152                           NaN
153                           NaN

                                      Facility Address Facility Neighborhood  \
0                               1220 Washington Street              SouthEnd
1           684 Centre Street\nJamaica Plain, MA 02130          JamaicaPlain
2                                    54a Hyde Park Ave          JamaicaPlain
3    90 canal street 4th floor \nBoston mass 02114\...                Boston
4                           464 Hanover Street, Unit A              NorthEnd
..                                                 ...                   ...
149                                  533 Washington St            Dorchester
150                                       882 South St            Roslindale
151                                  538 Blue Hill Ave               Roxbury
152                                   259 Cambridge St               Allston
153                                 1589 Blue Hill Ave              Mattapan

    Facility Zip Code                          Type of Marijuana License  \
0               02118            Recreational retail cannabis dispensary
1               02130            Recreational retail cannabis dispensary
2               02130  Co-located recreational and medical cannabis d...
3               02114                                                NaN
4               02113  Recreational retail cannabis dispensary;Delive...
..                ...                                                ...
149               NaN                               Adult use dispensary
150               NaN                               Adult use dispensary
151               NaN                               Adult use dispensary
152               NaN                               Adult use dispensary
153               NaN                               Adult use dispensary

                                    Application Status  \
0                                         Under review
1                               Conditionally approved
2                                   Open for operation
3                                            Withdrawn
4                      Complete equity pending hearing
..                                                 ...
149  Approved BCB - Executed HCA - Pending CCC - Eq...
150          Approved BCB - Executed HCA - Pending CCC
151                                           Inactive
152          Approved BCB - Executed HCA - Pending CCC
153                                          Withdrawn

    Seeking Bos Equity Program Submitted Date Map Location  \
0                          Yes            NaN          NaN
1                          Yes            NaN           No
2                           No            NaN          Yes
3                          Yes            NaN           No
4                          Yes            NaN          NaN
..                         ...            ...          ...
149                        Yes      5/10/2019          Yes
150                         No      7/20/2018          Yes
151                         No      7/12/2018           No
152                         No      12/5/2018          Yes
153                        Yes      6/21/2018           No

     Main Contact Full Name First Contact Full Name Second Contact Full Name  \
0              Adenike John                     NaN                      NaN
1             Eric Lawrence                     NaN                      NaN
2             Joseph Lekach           Joseph Lekach                      NaN
3    Russell Rounbehler Jr.  Russell Rounbehler Jr.                      NaN
4              Liam Bennett                     NaN                      NaN
..                      ...                     ...                      ...
149               Mike Ross                     NaN                      NaN
150        Mitch Rosenfield                     NaN                      NaN
151           Dexter Miller                     NaN                      NaN
152         Marie St. Fleur                     NaN                      NaN
153            Tito Jackson                     NaN                      NaN

    Third Contact Full Name
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
..                      ...
149                     NaN
150                     NaN
151                     NaN
152                     NaN
153                     NaN

[154 rows x 14 columns]>

In [5]:
print(df3.keys())
print(df3.aggregate)

Index(['BusinessName', 'DBAName', 'Address', 'CITY', 'State', 'ZIP',
       'LICSTATUS', 'LICENSECAT', 'DESCRIPT', 'LicenseAddDtTm', 'dayphn',
       'Property_ID', 'Latitude', 'Longitude'],
      dtype='object')
<bound method DataFrame.aggregate of                                   BusinessName DBAName         Address  \
0                               # 7 RESTAURANT     NaN       225 Grove
1     100 Federal Market & Barista- 11th Floor     NaN     100 Federal
2                 100 Percent Delicias Express     NaN      656 Centre
3                          11 Dining -16th Fl.     NaN    200 Berkeley
4                                    110 Grill     NaN   25 Jan Karski
...                                        ...     ...             ...
3026                             ZESTO'S PIZZA     NaN      460 Centre
3027                                   Ziggy's     NaN  583 Washington
3028                                        Zo     NaN        92 State
3029                           Zuma Restaurant     NaN        1 Dalton
3030                       Zume's Coffee House     NaN        219 Main

               CITY State    ZIP LICSTATUS LICENSECAT  \
0      West Roxbury    MA  02132    Active         FT
1            Boston    MA  02110    Active         FT
2     Jamaica Plain    MA  02130    Active         FT
3            Boston    MA  02116    Active         FS
4        Dorchester    MA  02125    Active         FS
...             ...   ...    ...       ...        ...
3026  Jamaica Plain    MA  02130    Active         FT
3027       Brighton    MA  02135    Active         FT
3028         Boston    MA  02109    Active         FT
3029         Boston    MA  02115    Active         FS
3030    Charlestown    MA  02129    Active         FT

                           DESCRIPT       LicenseAddDtTm       dayphn  \
0     Eating & Drinking w/ Take Out  2007-03-23 15:20:59  10000000000
1     Eating & Drinking w/ Take Out  2021-01-12 10:37:24  16174345000
2     Eating & Drinking w/ Take Out  2017-11-28 10:27:47  18572505689
3                 Eating & Drinking  2019-12-20 09:32:17  10000000000
4                 Eating & Drinking  2018-11-29 14:14:04  19786929450
...                             ...                  ...          ...
3026  Eating & Drinking w/ Take Out  2011-04-28 08:54:10  16175242004
3027  Eating & Drinking w/ Take Out  2020-10-23 12:17:07  16178333508
3028  Eating & Drinking w/ Take Out  2011-12-16 09:44:46  16179016017
3029              Eating & Drinking  2018-02-16 10:18:58  18574492500
3030  Eating & Drinking w/ Take Out  2007-07-07 12:23:40  16172420038

      Property_ID   Latitude  Longitude
0        156965.0  42.261873 -71.157410
1         57150.0  42.354770 -71.056130
2         28152.0  42.312830 -71.113860
3        187943.0  42.349860 -71.072910
4        421286.0   0.000000   0.000000
...           ...        ...        ...
3026      28061.0  42.319350 -71.111540
3027     351055.0   0.000000   0.000000
3028     170003.0  42.359232 -71.055320
3029     351070.0   0.000000   0.000000
3030      88457.0  42.376540 -71.065421

[3031 rows x 14 columns]>

In [6]:
print(df4.keys())
print(df4.aggregate)

Index(['license_num', 'historicallicensenum', 'status', 'license_category',
       'license_type', 'issued', 'expires', 'business_name', 'dba_name',
       'comments', 'location_comments', 'opening', 'closing', 'patronsout',
       'capacity', 'applicant', 'manager', 'day_phone', 'evening_phone',
       'address', 'city', 'state', 'zip', 'gpsx', 'gpsy'],
      dtype='object')
<bound method DataFrame.aggregate of      license_num historicallicensenum  status license_category  \
0      LB-485386                  NaN  Active             Misc
1      LB-492447                  NaN  Active               CV
2      LB-481088                  NaN  Active               CV
3      LB-423922                  NaN  Active               CV
4      LB-469103                  NaN  Active               CV
...          ...                  ...     ...              ...
3323   LB-112203                  NaN  Active             Misc
3324   LB-112204                  NaN  Active             Misc
3325   LB-108942                  NaN  Active               CV
3326   LB-109265                  NaN  Active               CV
3327   LB-107749                  NaN  Active               CV

                          license_type      issued     expires  \
0                     Retail Malt Wine         NaN         NaN
1                    Common Victualler  2022-10-03  2022-12-31
2     CV7ALN - Neighborhood Restricted  2022-09-29  2022-12-31
3                    Common Victualler  2022-09-28  2022-12-31
4                    Common Victualler  2022-09-27  2022-12-31
...                                ...         ...         ...
3323                         Dormitory  2013-09-16  2023-04-30
3324                         Dormitory  2013-09-16  2023-04-30
3325                 Common Victualler  2013-09-04  2022-12-31
3326                 Common Victualler  2013-08-30  2022-12-31
3327                 Common Victualler  2013-08-29  2022-12-31

                       business_name                       dba_name  \
0              Dorchester Market LLC              Dorchester Market
1                  Tori EB Food Inc.                     Tori Japan
2                      Yak Thai Inc.                       Thonglor
3                           PNR, LLC             PICK N' ROLL SUSHI
4             Airist Boston Co, Inc.                  Airist Boston
...                              ...                            ...
3323   TRUSTEES OF BOSTON UNIVERSITY              BOSTON UNIVERSITY
3324   TRUSTEES OF BOSTON UNIVERSITY              BOSTON UNIVERSITY
3325  WHOLE FOODS MARKET GROUP, INC.             Whole Foods Market
3326    Sultana's Bakery & Cafe, LLC  Boston Croissant Bakery, Cafe
3327              Xi Cha Corporation                         Xi Cha

                                           comments  ...  \
0                                               NaN  ...
1                                               NaN  ...
2                                               NaN  ...
3     Hours Operation Monday Saturday 11 00 AM 8 PM  ...
4                                               NaN  ...
...                                             ...  ...
3323                                  No Conditions  ...
3324                                  No Conditions  ...
3325                                            NaN  ...
3326            1 7 00 AM PM Mon Sat 9 6 on Sundays  ...
3327                                            NaN  ...

                                 applicant           manager      day_phone  \
0                    Dorchester Market LLC       Peter McGee  (617)238-7406
1                        Tori EB Food Inc.           Min Zhu  (781)609-8753
2                            Yak Thai Inc.   Piyapong Wongla  (781)472-0835
3                                 PNR, LLC       Victor Choi  (617)251-5829
4     Airist Boston Airist Boston Co, Inc.      Oh Kwan Kwon            NaN
...                                    ...               ...            ...
3323         Trustees of Boston University   NISHMIN KASHYAP  (617)353-5589
3324         Trustees of Boston University   NISHMIN KASHYAP  (617)353-5589
3325         Whole Foodsmarket Group, Inc.  Dorothy Pumphrey  (617)492-5500
3326          Sultana's Bakery & Cafe, LLC        Lale Dogar  (617)202-5454
3327                    Xi Cha Corporation            Ya Jia  (781)816-3128

      evening_phone                             address         city state  \
0               NaN                 951-  Dorchester AV   Dorchester    MA
1               NaN             62-  William C Kelly SQ  East Boston    MA
2               NaN                 559-  Washington ST     Brighton    MA
3               NaN                   134-  Boylston ST       Boston    MA
4               NaN  500     Logan Airport Terminal E    East Boston    MA
...             ...                                 ...          ...   ...
3323  (978)462-2373                 834-836   Beacon ST       Boston    MA
3324  (978)462-2373                    872-   Beacon ST       Boston    MA
3325            NaN                      27-  Austin St  Charlestown    MA
3326            NaN            1585-   Commonwealth AVE     Brighton    MA
3327  (857)383-1009                  350-  Longwood AVE       Boston    MA

        zip           gpsx          gpsy
0     02125  775975.718316  2.941310e+06
1     02128  780480.291321  2.961768e+06
2     02135  747073.290888  2.952562e+06
3     02116  773444.046428  2.953698e+06
4     02128       0.000000  0.000000e+00
...     ...            ...           ...
3323  02215  763472.605939  2.951897e+06
3324  02215  763046.220210  2.951738e+06
3325  02129  773358.251506  2.962150e+06
3326  02135  752659.000009  2.950680e+06
3327  02115  762561.013303  2.948507e+06

[3328 rows x 25 columns]>

In [7]:
# data cleaning - remove NaN values, removing duplicates

# removes all columns with over 200 NaN values
def drop_na(df):
    null_values = df.isnull().sum()
    null_index = null_values[null_values > 200].index
    print("Deleted", df[null_index])
    df.drop(null_index, axis = 1, inplace = True)
    return df

df1 = drop_na(df1)
df2 = drop_na(df2)
df3 = drop_na(df3)
df4 = drop_na(df4)

Deleted      historicallicensenum                                           comments  \
0                     NaN                                                NaN
1                     NaN                                                NaN
2                     NaN                                                NaN
3                     NaN                                                NaN
4                     NaN                                                NaN
...                   ...                                                ...
1441           GOPWML0008  MUST RECEIVE PRIOR WRITTEN PERMISSION BOARD AN...
1442            GOPWM0004  1 CONSUMPTION ALCOHOL ALLOWED IN SEATING AREA ...
1443           GOPWML0009                                                NaN
1444           SPCMWA0012                                                NaN
1445            GOPWM0001                                       11 00 M to P

                                      location_comments opening patronsout  \
0     Accessory retail sales of wine & malt beverage...     NaN        NaN
1     1,000SF: in one room on first floor (seating f...     NaN   11:30 PM
2     homestead bakery & cafe LLC is located on the ...     NaN   10:30 PM
3                                                   NaN     NaN        NaN
4     Logan International Airport, Terminal A, space...     NaN        NaN
...                                                 ...     ...        ...
1441  WITHIN THE CUTLER MAJESTIC THEATRE AUDITORIUM ...     NaN   12:30 AM
1442  IN WHOLE OF ORPHEUM THEATRE, INCLUDING BAR SER...     NaN   MIDNIGHT
1443  Entrance on first floor;  one room on first fl...     NaN    2:30 AM
1444                                                NaN     NaN    1:30 AM
1445  140 CLARENDON STREET; ON THE SECOND FLOOR THEA...     NaN   11:30 PM

          day_phone  evening_phone
0     (617)238-7406            NaN
1     (781)472-0835            NaN
2     (617)858-0468            NaN
3     (617)708-0775            NaN
4     (305)898-7414            NaN
...             ...            ...
1441            NaN  (617)894-6100
1442            NaN  (781)659-9923
1443            NaN  (617)608-0899
1444            NaN  (781)334-2856
1445            NaN       776-8280

[1446 rows x 7 columns]

In [14]:
# - replacing missing values with mean values

def replace_with_mean(df):
    for col_name in df.keys():
        if df[col_name].dtypes == float64 or int:
            mean = df[col_name].mean()
            df[col_name].replace(np.nan, mean, inplace = True)
    return df

df1 = replace_with_mean(df1)
df2 = replace_with_mean(df2)
df3 = replace_with_mean(df3)
df4 = replace_with_mean(df4)

'"\ndef replace_with_mean(df):\n    for col_name in df.keys():\n        if df[col_name].dtypes == float64 or int:\n            mean = df[col_name].mean()\n            df[col_name].replace(np.nan, mean, inplace = True)\n    return df\n\ndf1 = replace_with_mean(df1)\ndf2 = replace_with_mean(df2)\ndf3 = replace_with_mean(df3)\ndf4 = replace_with_mean(df4)\n'

In [10]:
# data normalization